version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: celery
    versions:
    - ">= 5.0.a, < 5.1"
  - dependency-name: black
    versions:
    - 21.4b0
    - 21.4b1
  - dependency-name: pydantic
    versions:
    - "1.8"
  - dependency-name: gunicorn
    versions:
    - 20.0.4
  - dependency-name: sentry-sdk
    versions:
    - 0.20.0
    - 0.20.1
    - 0.20.2
  - dependency-name: slack-sdk
    versions:
    - 3.3.0
    - 3.3.2
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: css-loader
    versions:
    - 5.0.1
    - 5.0.2
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
    - 5.2.1
    - 5.2.2
  - dependency-name: date-fns
    versions:
    - 2.16.1
    - 2.17.0
    - 2.18.0
    - 2.19.0
    - 2.20.0
    - 2.20.1
    - 2.20.2
    - 2.20.3
  - dependency-name: jspdf
    versions:
    - 2.3.1
  - dependency-name: vue-eslint-parser
    versions:
    - 7.4.1
    - 7.5.0
  - dependency-name: vue-stripe-elements-plus
    versions:
    - 0.3.2
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: python
    versions:
    - 3.9.1
    - 3.9.2
    - 3.9.3
  - dependency-name: node
    versions:
    - "15"
