version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  labels:
    - "npm"
    - "dependencies"
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  labels:
    - "docker"
    - "dependencies"
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  labels:
    - "python"
    - "dependencies"
