repos:
  -
    repo: 'https://github.com/prettier/prettier'
    rev: 1.15.3
    hooks:
      -
        id: prettier
        files: '^static/js/src/.*\.(js|json|vue)'
  -
    repo: https://github.com/ambv/black
    rev: stable
    hooks:
      -
        id: black
        types: [python]
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: trailing-whitespace
