repos:
  -
    repo: 'https://github.com/prettier/prettier'
    rev: 2.2.1
    hooks:
      -
        id: prettier
        files: '^static/js/src/.*\.(js|json|vue)'
  -
    repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
      -
        id: black
        types: [python]
  -
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: trailing-whitespace
